'use client';

import { useEffect } from 'react';
import { useCart } from '@/components/Cart/CartContext';

/**
 * Exposes the shop's real actions to AI agents through the WebMCP browser API
 * (navigator.modelContext.provideContext).
 *
 * Only tools backed by something that actually works are registered: catalogue
 * lookups read the static JSON generated by scripts/build-agent-assets.mjs, and
 * the cart tools drive the same client-side cart the UI uses. Nothing here
 * claims to place an order — checkout on this site is a stub that collects a
 * request, so there is no order tool to offer.
 */

type ToolResult = { content: { type: 'text'; text: string }[] };

type ToolDefinition = {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  execute: (args: Record<string, unknown>) => Promise<ToolResult>;
};

declare global {
  interface Navigator {
    modelContext?: {
      provideContext: (context: { tools: ToolDefinition[] }) => void;
    };
  }
}

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

const text = (value: unknown): ToolResult => ({
  content: [{ type: 'text', text: typeof value === 'string' ? value : JSON.stringify(value, null, 2) }],
});

async function loadIndex() {
  const res = await fetch(`${BASE}/api/index.json`);
  if (!res.ok) throw new Error(`Не удалось загрузить каталог (${res.status})`);
  return res.json();
}

async function loadCategory(slug: string) {
  const res = await fetch(`${BASE}/api/catalog/${slug}.json`);
  if (!res.ok) throw new Error(`Категория «${slug}» не найдена`);
  return res.json();
}

export function WebMcpTools() {
  const { addItem, open } = useCart();

  useEffect(() => {
    const modelContext = navigator.modelContext;
    if (!modelContext?.provideContext) return;

    const tools: ToolDefinition[] = [
      {
        name: 'pion_get_shop_info',
        description:
          'Контакты салона цветов «Пион» в Перми: телефон, адрес, режим работы, соцсети и список категорий каталога.',
        inputSchema: { type: 'object', properties: {}, additionalProperties: false },
        execute: async () => {
          const index = await loadIndex();
          return text({
            name: index.name,
            phone: index.phone,
            address: index.address,
            openingHours: index.openingHours,
            social: index.social,
            categories: index.categories.map((c: { slug: string; title: string; productCount: number }) => ({
              slug: c.slug,
              title: c.title,
              productCount: c.productCount,
            })),
          });
        },
      },
      {
        name: 'pion_list_products',
        description:
          'Список товаров категории с названием, составом, ценой в рублях и ссылкой на фото. Слаги категорий возвращает pion_get_shop_info.',
        inputSchema: {
          type: 'object',
          properties: {
            category: { type: 'string', description: 'Слаг категории, например bukety или roses' },
            limit: { type: 'number', description: 'Сколько товаров вернуть, по умолчанию 20' },
          },
          required: ['category'],
          additionalProperties: false,
        },
        execute: async (args) => {
          const category = String(args.category ?? '');
          const limit = Number(args.limit ?? 20);
          const data = await loadCategory(category);
          return text({
            category: data.title,
            total: data.products.length,
            products: data.products.slice(0, Math.max(1, limit)),
          });
        },
      },
      {
        name: 'pion_search_products',
        description:
          'Поиск товаров по названию или составу во всех категориях. Например «пионы», «розы», «шоколад».',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Поисковый запрос' },
            maxPrice: { type: 'number', description: 'Максимальная цена в рублях' },
          },
          required: ['query'],
          additionalProperties: false,
        },
        execute: async (args) => {
          const query = String(args.query ?? '').toLowerCase().trim();
          const maxPrice = args.maxPrice === undefined ? null : Number(args.maxPrice);
          const index = await loadIndex();
          const found: unknown[] = [];

          for (const category of index.categories) {
            if (category.productCount === 0) continue;
            const data = await loadCategory(category.slug);
            for (const product of data.products) {
              const haystack = `${product.title} ${product.composition}`.toLowerCase();
              if (query && !haystack.includes(query)) continue;
              if (maxPrice !== null && product.priceRub > maxPrice) continue;
              found.push({ ...product, category: category.slug, categoryTitle: category.title });
            }
          }

          return text({ query, matches: found.length, products: found.slice(0, 30) });
        },
      },
      {
        name: 'pion_add_to_cart',
        description:
          'Добавляет товар в корзину на этой странице и открывает её. Идентификатор товара — поле id из pion_list_products или pion_search_products.',
        inputSchema: {
          type: 'object',
          properties: {
            category: { type: 'string', description: 'Слаг категории товара' },
            id: { type: 'string', description: 'Идентификатор товара' },
          },
          required: ['category', 'id'],
          additionalProperties: false,
        },
        execute: async (args) => {
          const category = String(args.category ?? '');
          const id = String(args.id ?? '');
          const data = await loadCategory(category);
          const product = data.products.find((p: { id: string }) => p.id === id);
          if (!product) return text(`Товар ${id} не найден в категории «${category}».`);

          addItem({
            uid: product.id,
            title: product.title,
            price: product.priceRub,
            image: product.image ? product.image.replace(/^https?:\/\/[^/]+/, '') : '',
          });
          open();
          return text(
            `«${product.title}» (${product.priceRub} р.) добавлен в корзину. ` +
              'Заказ на сайте оформляется как заявка — оплату и доставку салон согласует по телефону.',
          );
        },
      },
    ];

    modelContext.provideContext({ tools });
  }, [addItem, open]);

  return null;
}
